[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
game = "Bm6LM1dhfnVDCSah6h8tMayYA5yRKT29KUMuMRScQ5ee"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
